examples/contract_details.rs, examples/stream_bars.rs, src/client.rs, src/client/tests.rs, src/market_data/historical.rs
* #101. Server time is now optional. If it can't be parsed will not cause a connection failure. However, there is a a change we don't determine timezone.
=> #101 Optional server time

Cargo.toml, src/client/transport.rs, src/messages.rs, src/messages/tests.rs
Log error instead of panicking when determining the request id index of a message. Logs can be used to later add support for said message.
=> Don't panic on unsupported messages.

src/orders.rs
TWS will sometimes return `UNSET_INTEGER` (`2**31 -1`), causing the code to panic. This will prevent enumerating the orders from `Client::executions(...)`. This is compliant with the C# client [behavior](https://github.com/quantrocket-llc/ibapi/blob/e3542aa3e05a2b752eb33742f81a50d4ac0aa1d8/source/csharpclient/client/Execution.cs#L31). Also, we note that the C# comment lists `0 = Unknown`.
=> Handle unknown liquidity as None

src/contracts.rs
Fixes #113 
- support for CRYPTO security type.
- to_field for CRYPTO
- from_field for CRYPTO
- convenience constructor with required exchange spec, PAXOS
Got past all errors in paper trading, except for account permissions errors.
=> crypto support and convenience constructor function

examples/historical_data_adjusted.rs, src/market_data/historical.rs, src/market_data/historical/tests.rs
Adds AdjustedLast to market_data::historical::WhatToShow and also adds an example to document that WhatToShow::AdjustedLast can only be used with historical_data_ending_now() and not with historical_data()
=> Issue 179/AdjustedLast

Cargo.toml, README.md, src/errors.rs, src/market_data/historical.rs
* Ready for release 1.0.3
* Updates `historical_data` validation
=> Bump version -> 1.0.3

Cargo.toml, src/market_data/realtime.rs, src/market_data/realtime/decoders.rs, src/market_data/realtime/decoders/tests.rs, src/market_data/realtime/tests/subscription_tests.rs, src/market_data/realtime/tests/tick_by_tick_last_tests.rs
Contracts such as crypto can use fractional volume
=> Use floating point type for size

src/transport.rs
Fixes #217 
I am not sure how to test this properly.
=> Set `client_id` in ConnectionMetadata

src/market_data/historical.rs, src/market_data/historical/tests.rs
This implements:
-  From<&str> for the historical types WhatToShow, BarSize, Duration.
- From<String> for Duration.
- test for the Duration String parsing.
```rust
WhatToShow::from("MIDPOINT");
BarSize::from("Min");
Duration::from_str("3 D")?;
Duration::from("3 D");
Duration::from("3 D").to_string());
```
=> add parsing from string for historical types

src/client.rs, src/contracts.rs, src/messages.rs, src/orders.rs, src/transport.rs, src/transport/connection.rs, src/transport/connection/tests.rs, src/transport/tests.rs
I noticed there is limited test coverage for the MessageBus, Connection and Dispatcher thread, and wanted to share an implementation that can improve the coverage.
Here is an implementation (WIP) similar to what i'm using to perform integration tests against my own client.
TWS / Gateway is mocked and run on a thread, The IB reconnect routine is simulated and supports returning responses when requests are received.  The behaviour of the server can be configured at the start of the test by declaring the request & responses vectors similar how the `MessageBusStub` can be configured for each test.
The  difference between this implementation and the current `MessageBusStub`  is the ability to schedule the handshake, and closing the socket.
```rust
let messages = VecDeque::from(vec![ …
```
=> connection bus integration tests

src/client.rs, src/contracts.rs, src/transport.rs, src/transport/connection/tests.rs, src/transport/recorder.rs, src/transport/recorder/tests.rs
This PR finalizes the connection tests - anything that was marked as TODO is now completed.
Code coverage for transport.rs has increased to 66.7%
Here are a list of changes:
- All connection tests are passing and bytestrings are fixed.
- message bus `start_cleanup_thread()` modified to accept a duration - tests can now start this thread with a different delay. This decreases the test time for tests using the message bus. it takes 0.01s to run the test suite (including connection tests, excluding examples)
- contract_details() now propagates any Errors encountered. Previously it returned an empty vec instead of Error::ConnectionReset. This fixes the test `test_contract_details_disconnect_raises_error`
- improvements to the mock server - Sometimes the dispatcher thread reads eagerly before …
=> finalize connection tests

src/accounts.rs, src/accounts/decoders/tests.rs, src/accounts/encoders.rs, src/accounts/encoders/tests.rs, src/accounts/tests.rs, src/client.rs, src/testdata/responses.rs
This commit introduces a comprehensive suite of new and updated tests for the `accounts` module, significantly improving test coverage across its sub-modules: `decoders`, `encoders`, and the main `accounts.rs` logic.
Key improvements include:
1.  **`accounts::decoders`**:
*   Added versioning tests for `decode_position` to handle messages with different field sets based on version.
*   Implemented table-driven tests for `decode_account_portfolio_value` to cover various `message_version` and `server_version` permutations affecting field presence and interpretation.
*   Added versioning tests for `decode_account_value`.
*   Included new tests for `decode_account_update_time`.
*   Enhanced `decode_family_codes` tests to cover empty lists and multiple codes.
2.  **`accounts::encoders`**:
* …
=> Tests: Enhance test coverage for the accounts module

src/news.rs, src/news/decoders.rs
Historical news timestamps are now parsed as UTC instead of using client-specific timezone
settings to ensure consistent timezone handling across different client configurations
Changes Made
- Modified decode_historical_news() to parse timestamps as UTC instead of using the client's timezone
- Removed dependency on client timezone parameter in news article decoding
- Renamed internal function to parse_time_as_utc() for clarity
- Updated function signatures to reflect that timezone parameter is no longer used
This addresses issue #233 by standardizing historical news timestamp handling to UTC, preventing timezone-related inconsistencies.
=> Fix timezone handling for historical news data

src/prelude.rs, src/transport.rs
When an execution message is received for an order, the system now properly stores the execution ID mapping to enable commission reports to be routed to the correct order channel
Fixes #256
=> Fix execution-to-order mapping

Cargo.toml, examples/submit_order.rs, src/client.rs, src/errors.rs, src/orders.rs, src/orders/tests.rs, src/prelude.rs, src/stubs.rs, src/transport.rs
- Add `submit_order` method for fire-and-forget order submission without subscriptions
- Add `order_update_stream` method to monitor all order updates through a single subscription
- Bump version to 1.2.0
This PR introduces two new methods for more flexible order management in rust-ibapi:
A new method that allows submitting orders without returning a subscription. This is useful when you don't need to track individual order updates through a dedicated subscription.
Creates a single subscription that receives updates for ALL orders placed through the client connection, including:
- Order status changes (submitted, filled, cancelled, etc.)
- Open order information
- Execution data for trades
- Commission reports
- Order-related messages
- Added `send_message` method to transport layer for …
=> feat: add submit_order and order_update_stream methods

examples/readme_historical_data.rs, examples/readme_multi_threading_1.rs, examples/readme_multi_threading_2.rs, src/transport.rs
- Improved log messages in `transport::process_orders` to avoid misleading warnings
- Modified `send_order_update` to return a boolean indicating successful message delivery
- Only log "could not route message" when the message wasn't routed to any channel (including order update stream)
Previously, the code would log "could not route message" even when messages were successfully sent to the order update stream. This created misleading log entries suggesting messages were lost when they were actually handled.
- Changed `send_order_update` to return `bool` indicating if the message was sent
- Updated all callers to check this return value before logging warnings
- Now warnings are only logged when a message truly couldn't be routed anywhere
- Fixed import ordering in example files …
=> chore: improve order routing log messages

src/common/error_helpers.rs, src/common/retry.rs, src/common/test_utils.rs, src/wsh/async.rs, src/wsh/common/decoders.rs, src/wsh/common/mod.rs, src/wsh/common/stream_decoders.rs, src/wsh/common/test_data.rs, src/wsh/common/test_tables.rs, src/wsh/mod.rs, src/wsh/sync.rs
This PR refactors the Wall Street Horizon (WSH) module to use table-driven testing patterns and shared test infrastructure, following the same approach established in the accounts module. The refactoring eliminates code duplication, improves test maintainability, and ensures consistent testing between sync and async implementations.
- **Created shared test tables** in `src/wsh/common/test_tables.rs`
- `DecodeTestCase` struct for StreamDecoder decode tests
- `ApiTestCase` struct for API function tests  
- `EventDataByContractTestCase` struct for contract-specific tests
- Test data constants: `WSH_METADATA_DECODE_TESTS`, `WSH_EVENT_DATA_DECODE_TESTS`
- Test case generators: `wsh_metadata_test_cases()`, `event_data_by_contract_test_cases()`
- **Created shared test data** in …
=> Refactor WSH module to use table-driven tests and improve test infrastructure

Cargo.toml, MIGRATION.md, examples/record_interactions.rs, src/lib.rs, src/messages.rs, src/messages/parser_registry.rs, tws_interactions.yaml
- Added functionality to record and parse TWS API interactions for debugging and mock server development
- Implemented message parser registry that decodes raw TWS protocol messages into human-readable fields
- Created example demonstrating how to capture real interactions with proper data sanitization
When developing against the TWS API or creating mock servers for testing, it's valuable to:
1. Record real API interactions to understand the protocol
2. Parse raw messages into structured fields with descriptive names
3. Create test fixtures from live data (with sensitive info sanitized)
4. Debug issues by examining actual message exchanges
- **Message Parser Registry** (`src/messages/parser_registry.rs`): Provides structured parsing of TWS protocol messages
- Field-based parsers for …
=> Add interaction recording and message parsing for debugging and mock servers

src/client/async.rs, src/client/common.rs, src/client/sync.rs
This PR expands integration test coverage for client account-related methods using the established MockGateway patterns from #282.
- Added helper functions in `client/common.rs` for setting up MockGateway test scenarios
- Implemented integration tests for both sync and async client implementations
- Fixed compilation warnings related to unused imports
1. **`managed_accounts()`** - Retrieves list of managed accounts
2. **`positions()`** - Streams position updates  
3. **`account_summary()`** - Retrieves account summary with specific tags
4. **`pnl()`** - Streams P&L data
5. **`account_updates()`** - Streams account value and portfolio updates (currently ignored)
- All tests follow the same pattern established in #282
- Tests use actual TCP connections through MockGateway
- Message formats …
=> Add integration tests for client account methods

src/accounts/sync.rs, src/client/builders/async.rs, src/client/builders/sync.rs, src/client/sync.rs, src/market_data/historical/sync.rs, src/news/sync.rs, src/orders/sync.rs, src/subscriptions/common.rs
- Fixes all clippy warnings to ensure compatibility with Rust 1.89.0's stricter lifetime elision rules
- Updates both sync and async implementations to pass clippy with `-D warnings` flag
- Add `#[allow(dead_code)]` to unused `RESPONSE_MESSAGE_IDS` constant in `StreamDecoder` trait
- Fix lifetime elision warnings by adding explicit `'_` lifetime annotations to `Subscription` return types across:
- `src/accounts/sync.rs`
- `src/client/builders/async.rs`
- `src/client/builders/sync.rs`
- `src/client/sync.rs`
- `src/market_data/historical/sync.rs`
- `src/news/sync.rs`
- `src/orders/sync.rs`
- `src/subscriptions/common.rs`
=> Fix clippy warnings for Rust 1.89.0

src/client/async.rs, src/client/builders/async.rs, src/news/async.rs, src/orders/async.rs, src/scanner/async.rs, src/subscriptions/async.rs
- Remove Clone trait from async Client to prevent shared ownership issues
- Refactor subscription builders to use server_version and message_bus directly instead of client references
- Update subscription lifecycle management to avoid holding client references
The async Client was previously cloneable, which could lead to ownership and lifecycle issues. This PR removes the Clone trait and refactors all subscription-related code to work with the necessary components (server_version and message_bus) directly rather than holding references to the entire client.
- **client/async.rs**: Removed `#[derive(Clone)]` from Client struct
- **client/builders/async.rs**: Updated all builders to use `server_version` and `message_bus` instead of client references
- **subscriptions/async.rs**: Changed …
=> Fix client ownership and subscription lifecycle

CLAUDE.md, Cargo.toml, examples/async/connection_monitoring.rs, examples/sync/connection_monitoring.rs, justfile, src/client/async.rs, src/client/sync.rs, src/connection/async.rs, src/connection/sync.rs, src/stubs.rs, src/transport/async.rs, src/transport/common.rs, src/transport/mod.rs, src/transport/sync.rs
This PR addresses issue #300 by implementing `Client.is_connected()` to allow monitoring of connection status in long-running applications. Additionally, it adds full reconnection support to the async transport layer, bringing it to feature parity with the sync implementation.
- Added `is_connected()` method to both sync and async `Client` implementations
- Tracks connection state using `AtomicBool` in MessageBus implementations
- Updates connection state appropriately on errors, resets, and reconnections
- Provides simple boolean check without blocking or async operations
- Implemented `AsyncConnection::reconnect()` with Fibonacci backoff strategy
- Added automatic reconnection on connection errors (matching sync behavior)
- Properly resets channels after successful reconnection
- Uses …
=> feat: Add Client.is_connected() method and async reconnection support

src/client/async.rs, todos/client-api-review-v2.0.md
- Changed visibility of 5 internal async client methods from `pub` to `pub(crate)`
- Updated client API review document to reflect these fixes
- Ensures proper encapsulation of implementation details
This PR addresses visibility issues identified in the v2.0 API review by properly hiding internal implementation methods in the async client:
- `send_request()` - Internal method for sending requests
- `send_shared_request()` - Internal method for shared requests  
- `send_order()` - Internal method for order submission
- `send_message()` - Internal method for sending messages
- `create_order_update_subscription()` - Internal subscription creation
These methods are implementation details that should not be exposed in the public API. They remain accessible to the crate internals where needed. …
=> fix: hide async client internal methods from public API
