Cargo.toml
=> Release 0.2.0

src/client.rs, src/orders.rs, src/orders/order_builder.rs
=> Housekeeping

Cargo.toml, contributors/README.md, examples/tick_by_tick.rs, src/accounts/decoders.rs, src/client.rs, src/client/transport.rs, src/contracts/encoders.rs, src/contracts/tests.rs, src/market_data/historical.rs, src/market_data/historical/encoders.rs, src/market_data/realtime.rs, src/stubs.rs
Cleanup some warnings. Prep for release 0.5.0
=> Code hygiene

src/messages.rs, src/transport.rs
Increases read timeout when receiving data from TWS. Certain hardware/software configurations my require more time.
=> Increases read timeout

src/transport.rs
Accounts for case where Unix and Windows may return different error codes upon timeout.
=> Handle platform specific codes

Cargo.toml, examples/scanner_subscription_active_stocks.rs, examples/scanner_subscription_complex_orders.rs, src/messages.rs, src/messages/tests.rs, src/scanner.rs, src/scanner/decoders.rs, src/scanner/decoders/tests.rs, src/testdata/responses.rs
Fixes parsing of scanner response of complex orders
=> Scanner bug

Cargo.toml, examples/completed_orders.rs, examples/place_order.rs, src/messages/shared_channel_configuration.rs
Fixes mapping of request and responses for requesting completed orders.
=> Fix completed orders regression

src/accounts.rs
=> Derive Serialize and Deserialize for structs in `account.rs`

Cargo.toml, src/scanner.rs, src/scanner/tests.rs
Cancels scanner data subscription when subscription is dropped
=> Cancel scanner subscription

src/contracts.rs, src/messages/tests.rs
* Adds support for contract for difference security types
* Puts unknown security types into `Other`
=> Support CFD security type

src/client.rs, src/contracts.rs, src/contracts/decoders/tests.rs, src/market_data/historical.rs, src/messages/tests.rs, src/transport.rs
* Adds additional tests for contracts decoding
* Cleans up clippy warning
=> Test coverage

src/contracts/decoders/tests.rs, src/contracts/tests.rs
1. Comprehensive Test Implementation:
- Implemented detailed test cases for various contract types (stock, bond, future, option)
- Added tests for contract constructors, security type conversions, and contract verification
- Implemented tests for market rules, option price calculations, and implied volatility
2. Test Pragmas:
- Added #[ignore = "reason: need sample messages"] attributes to three test functions that require actual sample messages:
- request_bond_contract_details
- request_future_contract_details
- request_matching_symbols
3. Error Handling Tests:
- Added test cases for various error conditions in contract details requests
- Implemented tests for server version compatibility checks
Technical Details
- Tests now cover contract details requests for different security types
- …
=> Enhanced Contract Tests Module

src/market_data/historical/tests.rs
- Significantly expanded test coverage for the market_data::historical module
- Added comprehensive test cases for histogram data, head timestamp, and other historical data functions
- Improved test infrastructure with better assertions and validation
=> Enhance test coverage for historical market data module

src/contracts.rs, src/contracts/tests.rs, src/market_data/historical/tests.rs
**Description**
This PR introduces a new `ContractBuilder` that provides a fluent, type-safe API for creating `Contract` instances with built-in validation. The builder pattern makes contract creation more ergonomic
and helps prevent common configuration errors.
**Key Features**
- Fluent API: Method chaining for intuitive contract configuration
- Type-safe validation: Compile-time and runtime checks for contract requirements
- Convenience methods: Pre-configured builders for common contract types (stock(), futures(), crypto(), option())
- Comprehensive validation: Ensures required fields are set based on security type
- Zero breaking changes: Existing Contract API remains unchanged
**Usage Examples**
```rust
// Create a stock contract
let contract = ContractBuilder::stock("AAPL", …
```
=> Add ContractBuilder for fluent Contract creation

Cargo.toml, examples/readme_connection.rs, examples/readme_historical_data.rs, examples/readme_multi_threading_1.rs, examples/readme_multi_threading_2.rs, examples/readme_place_order.rs, examples/readme_realtime_data_1.rs, examples/readme_realtime_data_2.rs, src/client.rs, src/contracts.rs, src/contracts/tick_types.rs, src/lib.rs, src/market_data.rs, src/market_data/realtime.rs, src/news.rs, src/orders.rs, src/server_versions.rs, src/wsh.rs
This PR improves documentation consistency and fixes issues in the example files.
1. **Fixed example file imports** - Updated all `readme_*.rs` example files to use `ibapi::prelude::*` imports to match what's shown in the README
2. **Fixed type names** - Changed type names to match prelude exports (e.g., `BarSize` → `HistoricalBarSize`/`RealtimeBarSize`)
3. **Fixed bug in readme_realtime_data_2.rs** - Corrected swapped values in print statement
4. **Improved documentation formatting** - Fixed list formatting in `news.rs` and `orders.rs` for better readability
- Enhanced documentation for various enums and structs
- Added missing documentation for tick types and server versions
- Improved formatting of multi-line documentation comments
=> Documentation improvements and example fixes

src/accounts/async.rs, src/accounts/common/mod.rs, src/accounts/common/test_data.rs, src/accounts/sync.rs, src/accounts/types.rs
This PR adds comprehensive test coverage for both the sync and async implementations of the accounts module, significantly improving test robustness, error handling validation, and edge case coverage.
- **Before**: 11 tests
- **After**: 24 tests (+13 new tests)
- **New test code**: ~347 lines
- **Before**: 11 tests
- **After**: 21 tests (+10 new tests)
- **New test code**: ~320 lines
- **Total tests**: 45 (up from 22)
- **Total new test code**: ~667 lines
- **Coverage areas**: Version checking, error handling, edge cases, parameter validation, concurrency, lifecycle management
- **Server version compatibility**: Tests all functions reject requests when server version is too old
- **Error response handling**: Tests empty responses, no responses, invalid inputs
- **Parse error handling**: …
=> Add comprehensive test coverage for accounts module (sync and async)

CONTRIBUTING.md
This PR significantly updates the CONTRIBUTING.md file to reflect the new sync/async architecture and established patterns in the rust-ibapi codebase. The documentation now provides comprehensive guidance for contributors working with the dual-mode architecture.
- **Sync/Async Overview**: Added detailed explanation of the dual-mode architecture
- **Feature Flags**: Documented the mutually exclusive `sync` and `async` features
- **Module Organization**: Documented the standard module structure pattern:
```
src/<module>/
├── mod.rs         # Public types and module exports
├── common/        # Shared implementation details
│   ├── encoders.rs # Message encoding functions
│   ├── decoders.rs # Message decoding functions
│   └── test_data.rs # Shared test fixtures
├── sync.rs        # …
```
=> docs: update CONTRIBUTING.md with comprehensive sync/async architecture guidance

src/contracts/async.rs, src/contracts/common/mod.rs, src/contracts/common/stream_decoders.rs, src/contracts/common/test_tables.rs, src/contracts/sync.rs, src/protocol.rs, src/stubs.rs, src/transport/async.rs
This PR refactors the contracts module to follow the same clean architecture patterns established in the wsh module, improving code organization and reducing duplication between sync/async implementations.
- Created `common/stream_decoders.rs` to extract shared StreamDecoder implementations
- Created `common/test_tables.rs` with comprehensive table-driven test data
- Updated both sync and async implementations to use common decoders
- Eliminated duplicate StreamDecoder implementations between sync/async
- Converted all tests to table-driven format for better maintainability
- Fixed test data formats to match actual decoder expectations
- Added missing protocol version constants to Features module
- All tests passing in both sync and async modes
- Added test-only `request_messages()` …
=> Refactor contracts module to align with wsh patterns

src/client/async.rs, src/client/common.rs, src/client/sync.rs
This PR refactors the client integration tests to ensure consistency between sync and async implementations. The changes improve the MockGateway API and align test patterns across both modes.
- Added internal address storage with `address()` getter method
- Changed `start()` return type to `Result<(), anyhow::Error>` for better error handling
- MockGateway now manages its own state internally
- `setup_connect()` now returns just `MockGateway`
- `setup_server_time()` returns `(MockGateway, ServerTimeExpectations)` 
- `setup_managed_accounts()` returns `(MockGateway, ManagedAccountsExpectations)`
- Other setup functions return just `MockGateway`
- All tests now use `gateway.address()` instead of separate address parameters
- Added expectations structs for type-safe test data
- Added missing …
=> Refactor client integration tests for consistency

.gitignore, CLIENT_INTEGRATION_TEST_TRACKING.md, OPEN_ITEMS.md, src/client/async.rs, src/client/common.rs, src/client/sync.rs, src/connection/async.rs, src/messages.rs, src/transport/routing.rs, src/transport/sync.rs
- Added comprehensive integration tests for account management methods using MockGateway
- Fixed PortfolioValue decoding issue in account_updates test  
- Documented test coverage and known architecture issues
Added integration tests for the following Client methods (both sync and async):
- `next_valid_order_id()` - Tests order ID retrieval
- `positions_multi()` - Tests multi-account position queries
- `pnl_single()` - Tests single contract P&L tracking
- `account_updates()` - Fixed and re-enabled previously failing test
- `account_updates_multi()` - Tests multi-account updates
- `family_codes()` - Tests family code retrieval
- Fixed `account_updates` test by correcting PortfolioValue message format (version 4 instead of 3)
- Resolved shared channel routing issue for FamilyCodes in async …
=> Add integration tests for account methods

CLIENT_INTEGRATION_TEST_TRACKING.md, src/client/async.rs, src/client/common.rs, src/client/sync.rs
This PR adds MockGateway-based integration tests for all historical data methods in the Client, significantly improving test coverage from ~45% to ~78%.
- `head_timestamp()` - Tests retrieving earliest data timestamp
- `historical_data()` - Tests fetching historical bar data
- `historical_schedules()` - Tests retrieving trading session schedules
- `historical_ticks_bid_ask()` - Tests fetching historical bid/ask tick data
- `historical_ticks_mid_point()` - Tests fetching historical midpoint tick data
- `historical_ticks_trade()` - Tests fetching historical trade tick data
- `histogram_data()` - Tests retrieving price distribution histogram
- Created MockGateway setup functions for each historical method in `src/client/common.rs`
- Implemented tests for both sync and async Client variants
- …
=> Add comprehensive integration tests for historical data methods

src/client/builders/async.rs, src/client/builders/common.rs, src/client/builders/sync.rs, src/client/error_handler.rs, src/messages.rs, src/messages/tests.rs, src/subscriptions/common.rs
Significantly improved test coverage across multiple client-related modules with comprehensive table-driven tests.
- **Added table-driven tests** for all `ResponseMessage` parsing methods (int, long, double, string, bool, datetime)
- **Fixed bug in `peek_int()`** - was incorrectly checking `self.i` instead of parameter `i` for bounds checking
- **Added tests for `encode_length`** function with various input scenarios
- **Comprehensive boundary testing** for message parsing operations
- **Added tests for special field extraction** (order_id, execution_id)
- **Tested encode/decode roundtrip** functionality
- **Added comprehensive tests** for all builder types:
- RequestBuilder
- SharedRequestBuilder
- OrderRequestBuilder
- MessageBuilder
- SubscriptionBuilder
- **Table-driven tests** for …
=> test: comprehensive test coverage improvements for client modules
